"""Build relocatable in-process hooks from the previously tested native recipes."""

import struct
from pathlib import Path
import native_warform as warform
import pe_utils

SERVER_FAKE = 0x60000000
CLIENT_FAKE = 0x70000000
IMAGE_BASE = 0x10000000
SERVER_CODE_SIZE = 0x800
SERVER_OFFSETS = {"sync": 0x000, "reentry": 0x100, "expire": 0x200,
                  "input": 0x400, "feat": 0x500, "extra": 0x600}
tracked_server = {}


class ServerCode(warform.Code):
    def __init__(self, va):
        super().__init__(va)
        self.external = []
        tracked_server[va] = self

    def jump(self, opcode, target):
        at = len(self.b) + len(bytes.fromhex(opcode))
        super().jump(opcode, target)
        if isinstance(target, int):
            self.external.append((at, 1, target - IMAGE_BASE, 0))

    def global_ptr(self, target, deref=False):
        at = len(self.b)
        super().global_ptr(target, deref)
        self.external.append((at + 8, 2, target - IMAGE_BASE, at + 5))


warform.Code = ServerCode


def sync_hook(va):
    code = ServerCode(va)
    code.emit("83bd6c140000007f0b8a85dc1e0000")
    code.jump("e9", 0x1016c55e)
    code.emit("30c0")
    code.jump("e9", 0x1016c55e)
    payload = code.finish()
    if len(payload) != 27:
        raise ValueError("Warform sync helper changed")
    return payload


server_blobs = {
    "sync": sync_hook(SERVER_FAKE),
    "reentry": warform.reentry(SERVER_FAKE + SERVER_OFFSETS["reentry"]),
    "expire": warform.expire(SERVER_FAKE + SERVER_OFFSETS["expire"]),
    "input": warform.input_owner(SERVER_FAKE + SERVER_OFFSETS["input"]),
    "feat": warform.feat_owner(SERVER_FAKE + SERVER_OFFSETS["feat"]),
    "extra": warform.extra_feat_owner(SERVER_FAKE + SERVER_OFFSETS["extra"]),
}
server_template = bytearray(SERVER_CODE_SIZE)
server_fixups = []
for name, payload in server_blobs.items():
    offset = SERVER_OFFSETS[name]
    if offset + len(payload) > SERVER_CODE_SIZE:
        raise ValueError("Warform helper exceeds allocation: " + name)
    server_template[offset:offset + len(payload)] = payload
    server_fixups.extend((offset + at, kind, target, offset + anchor)
                         for at, kind, target, anchor in tracked_server[SERVER_FAKE + offset].external)


class ClientCode(pe_utils.Code):
    def __init__(self, va):
        super().__init__(va)
        self.external = []

    def rel32(self, opcode, target):
        at = len(self.data) + len(bytes.fromhex(opcode))
        super().rel32(opcode, target)
        if isinstance(target, int):
            self.external.append((at, 1, target - IMAGE_BASE, 0))

    def global_ptr(self, opcode, target, anchor):
        self.emit(opcode)
        at = len(self.data)
        self.emit(struct.pack("<i", target - anchor))
        self.external.append((at, 2, target - IMAGE_BASE, anchor - self.va))


def filter_helper():
    code = ClientCode(CLIENT_FAKE)
    code.emit("e80000000059")
    anchor = CLIENT_FAKE + 5
    code.global_ptr("8b81", 0x1061992c, anchor)
    code.emit("83ff01")
    code.rel32("0f8c", 0x1019dab7)
    code.emit("3bf8")
    code.rel32("0f85", 0x1019da81)
    code.global_ptr("8bb1", 0x10619928, anchor)
    code.emit("8b4e048b11ff520484c0")
    code.rel32("0f85", 0x1019da81)
    code.emit("8b460483782c01")
    code.rel32("0f84", 0x1019dacd)
    code.rel32("e9", 0x1019da81)
    return code, code.finish()


client_code, client_blob = filter_helper()


def write_header(path, prefix, template, fixups, offsets):
    lines = ["/* Generated by generate_blobs.py; do not edit. */", "#pragma once", "#include <stdint.h>",
             "typedef struct { uint16_t offset; uint8_t kind; uint32_t target_rva; uint16_t anchor; } %sFixup;" % prefix,
             "enum { %s_CODE_SIZE = %d };" % (prefix.upper(), len(template))]
    for name, offset in offsets.items():
        lines.append("enum { %s_%s_OFFSET = 0x%x };" % (prefix.upper(), name.upper(), offset))
    lines.append("static const uint8_t k%sCode[%s_CODE_SIZE] = {" % (prefix, prefix.upper()))
    for at in range(0, len(template), 16):
        lines.append("    " + ", ".join("0x%02x" % byte for byte in template[at:at + 16]) + ",")
    lines.append("};")
    lines.append("static const %sFixup k%sFixups[] = {" % (prefix, prefix))
    for at, kind, target, anchor in sorted(fixups):
        lines.append("    { %d, %d, 0x%x, %d }," % (at, kind, target, anchor))
    lines.append("};")
    lines.append("enum { %s_FIXUP_COUNT = sizeof(k%sFixups) / sizeof(k%sFixups[0]) };" %
                 (prefix.upper(), prefix, prefix))
    path.write_text("\n".join(lines) + "\n", encoding="ascii")


root = Path(__file__).resolve().parents[1] / 'plugin'
write_header(root / "generated_server.h", "Server", server_template, server_fixups, SERVER_OFFSETS)
write_header(root / "generated_client.h", "Client", client_blob, client_code.external, {"filter": 0})
print("Generated Warform", len(server_fixups), "fixups and filter", len(client_code.external), "fixups")
