"""Generate relocatable x86 helpers from the verified native clock recipe."""

from pathlib import Path
import native_clock as native


CODE_BASE = 0x60000000
STATE = CODE_BASE + 0x400
ENGINE_BASE = 0x20000000

instances = {}


class TrackedCode(native.Code):
    def __init__(self, va):
        super().__init__(va)
        self.runtime_fixups = []
        instances[va] = self

    def branch(self, opcode, target):
        offset = len(self.b) + len(bytes.fromhex(opcode))
        super().branch(opcode, target)
        if isinstance(target, int) and not CODE_BASE <= target < CODE_BASE + 0x400:
            self.runtime_fixups.append((offset, 1, target - ENGINE_BASE, 0))

    def ptr(self, register, target):
        start = len(self.b)
        super().ptr(register, target)
        if target != STATE:
            raise ValueError("Unexpected state pointer")
        self.runtime_fixups.append((start + 8, 2, 0, start + 5))


native.Code = TrackedCode
blobs = (
    (0x000, native.sync(CODE_BASE, STATE)),
    (0x200, native.clock(CODE_BASE + 0x200, STATE, CODE_BASE)),
    (0x300, native.pause_message(CODE_BASE + 0x300, CODE_BASE)),
)
template = bytearray(0x400)
fixups = []
previous_end = 0
for offset, payload in blobs:
    if offset + len(payload) > len(template):
        raise ValueError("Clock helper exceeds its allocation")
    if offset < previous_end:
        raise ValueError("Clock helper regions overlap")
    template[offset:offset + len(payload)] = payload
    previous_end = offset + len(payload)
    fixups.extend((offset + at, kind, target, offset + anchor)
                  for at, kind, target, anchor in instances[CODE_BASE + offset].runtime_fixups)

sync_code = instances[CODE_BASE].b
iat_at = sync_code.find(bytes.fromhex("ff97"))
if iat_at < 0 or sync_code.find(bytes.fromhex("ff97"), iat_at + 1) >= 0:
    raise ValueError("Expected one sound-clock IAT access")
fixups.append((iat_at + 2, 3, native.PLAT_IAT - ENGINE_BASE, 0))

clock_code = instances[CODE_BASE + 0x200].b
pause_at = clock_code.find(bytes.fromhex("8b82"))
if pause_at < 0 or clock_code.find(bytes.fromhex("8b82"), pause_at + 1) >= 0:
    raise ValueError("Expected one pause-state access")
fixups.append((0x200 + pause_at + 2, 3, native.PAUSED - ENGINE_BASE, 0))

out = Path(__file__).with_name("generated_clock.h")
lines = ["/* Generated by generate_blobs.py; do not edit. */", "#pragma once",
         "#include <stdint.h>", "enum { CLOCK_CODE_SIZE = 0x400, CLOCK_CLOCK_OFFSET = 0x200, CLOCK_PAUSE_OFFSET = 0x300 };",
         "typedef struct { uint16_t offset; uint8_t kind; uint32_t target_rva; uint16_t anchor; } ClockFixup;",
         "static const uint8_t kClockCode[CLOCK_CODE_SIZE] = {"]
for at in range(0, len(template), 16):
    lines.append("    " + ", ".join("0x%02x" % byte for byte in template[at:at + 16]) + ",")
lines.append("};")
lines.append("static const ClockFixup kClockFixups[] = {")
for at, kind, target, anchor in sorted(fixups):
    lines.append("    { %d, %d, 0x%x, %d }," % (at, kind, target, anchor))
lines.append("};")
lines.append("enum { CLOCK_FIXUP_COUNT = sizeof(kClockFixups) / sizeof(kClockFixups[0]) }; ")
out.write_text("\n".join(lines) + "\n", encoding="ascii")
print("Generated", out, "with", len(fixups), "runtime relocations")
